### ISSUE TITLE
Cambiar ForeignKeys por OneToMany

### ISSUE THREAD

**Issue by nestor98** [UNIZAR-30226-2020-01/backend_django#3]
Ahora mismo django recomienda este cambio con estos warnings:

**Comment by nestor98** [comment]
```
System check identified some issues:

WARNINGS:
musica.Amigos.uno: (fields.W342) Setting unique=True on a ForeignKey has the same effect as using a OneToOneField.
        HINT: ForeignKey(unique=True) is usually better served by a OneToOneField.
musica.Cancionenlista.cancion: (fields.W342) Setting unique=True on a ForeignKey has the same effect as using a OneToOneField.
        HINT: ForeignKey(unique=True) is usually better served by a OneToOneField.
musica.Favoritos.audio: (fields.W342) Setting unique=True on a ForeignKey has the same effect as using a OneToOneField.
        HINT: ForeignKey(unique=True) is usually better served by a OneToOneField.
musica.Listaencarpeta.carpeta: (fields.W342) Setting unique=True on a ForeignKey has the same effect as using a OneToOneField.
        HINT: ForeignKey(unique=True) is usually better served by a OneToOneField.
```
